# Generated by Django 3.1.6 on 2021-08-29 11:23

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210326_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProAccessPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.IntegerField(choices=[(30, '1 bulan (30 hari)'), (90, '3 bulan (90 hari)'), (365, '1 tahun (365 hari)')])),
                ('price', models.IntegerField()),
                ('valid_until', models.DateTimeField(default=account.models.valid_until_time)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gifted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pro_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='account.proaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidtransPaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=200)),
                ('transaction_status', models.CharField(max_length=50)),
                ('fraud_status', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.proaccesspurchase')),
            ],
        ),
    ]
