# Generated by Django 3.1.6 on 2021-02-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210213_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=200, null=True, verbose_name='Github')),
                ('gitlab', models.CharField(blank=True, max_length=200, null=True, verbose_name='GitLab')),
                ('bitbucket', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bitbucket')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
