# Generated by Django 3.1.6 on 2021-11-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211024_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='link',
            name='bitbucket',
            field=models.URLField(blank=True, default='', help_text='Format: https://bitbucket.org/upkoding/', verbose_name='Bitbucket'),
        ),
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Format: https://www.facebook.com/upkoding', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='link',
            name='github',
            field=models.URLField(blank=True, default='', help_text='Format: https://github.com/upkoding', verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='link',
            name='gitlab',
            field=models.URLField(blank=True, default='', help_text='Format: https://gitlab.com/upkoding', verbose_name='GitLab'),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkedin',
            field=models.URLField(blank=True, default='', help_text='Format: https://www.linkedin.com/in/upkoding/', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.URLField(blank=True, default='', help_text='Format: https://twitter.com/upkoding', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Format: https://www.upkoding.com', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.URLField(blank=True, default='', help_text='Format: https://www.youtube.com/c/upkoding', verbose_name='Youtube'),
        ),
    ]
