# Generated by Django 3.1.6 on 2021-02-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210217_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bitbucket',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bitbucket'),
        ),
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='link',
            name='github',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='link',
            name='gitlab',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='GitLab'),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='link',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
