# Generated by Django 3.1.6 on 2021-02-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=100, verbose_name='Judul')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('requirements', models.JSONField(blank=True, null=True, verbose_name='Requirements')),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=projects.models.project_cover_path)),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tags')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('taken_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
