# Generated by Django 3.1.6 on 2021-03-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'ordering': ['-pk']},
        ),
    ]
