# Generated by Django 3.1.6 on 2021-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_short',
            field=models.CharField(default='', max_length=100, verbose_name='Deskripsi Pendek'),
        ),
    ]
