# Generated by Django 3.1.6 on 2021-02-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
