# Generated by Django 3.1.6 on 2021-09-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0001_initial'),
        ('projects', '0002_auto_20210317_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_premium'], name='project_is_premium_idx'),
        ),
    ]
