# Generated by Django 3.1.6 on 2021-10-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0001_initial'),
        ('projects', '0002_auto_20210317_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard'), (99, 'project')], default=1),
        ),
        migrations.AddField(
            model_name='userproject',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Active'), (3, 'Deleted'), (4, 'Archived')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprojectevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'project_start'), (1, 'progress_update'), (2, 'progress_complete'), (3, 'review_request'), (10, 'review_message'), (11, 'project_complete'), (12, 'project_incomplete')]),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['level'], name='project_level_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_premium'], name='project_is_premium_idx'),
        ),
    ]
