# Generated by Django 3.1.6 on 2021-08-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0001_initial'),
        ('projects', '0002_auto_20210317_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='codeblock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeblocks.codeblock'),
        ),
    ]
