# Generated by Django 3.1.6 on 2021-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210817_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_premium'], name='project_is_premium_idx'),
        ),
    ]
