# Generated by Django 3.1.6 on 2021-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210218_0427'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['user', 'project'], name='projects_us_user_id_4e02af_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproject',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
    ]
