# Generated by Django 3.1.6 on 2021-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210218_1219'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userproject',
            name='projects_us_user_id_4e02af_idx',
        ),
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['user', 'project'], name='user_project_idx'),
        ),
    ]
