# Generated by Django 3.1.6 on 2021-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210218_1220'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id', 'slug'], name='id_slug_idx'),
        ),
    ]
