# Generated by Django 3.1.6 on 2021-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210218_1230'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='id_slug_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='is_active_idx'),
        ),
    ]
