# Generated by Django 3.1.6 on 2021-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210218_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='require_demo_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='require_sourcecode_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproject',
            name='requirements_completed_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
