# Generated by Django 3.1.6 on 2021-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210220_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='requirements_completed_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
