# Generated by Django 3.1.6 on 2021-02-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20210222_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Progress'), (1, 'Pending Review'), (2, 'Need Revision'), (3, 'Complete'), (4, 'Incomplete')], default=0, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='UserProjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Project start'), (1, 'Progress update'), (2, 'Review request'), (10, 'Review message'), (11, 'Project complete'), (12, 'Project incomplete')])),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.userproject')),
            ],
        ),
        migrations.AddIndex(
            model_name='userprojectevent',
            index=models.Index(fields=['event_type'], name='user_project_event_type_idx'),
        ),
    ]
