# Generated by Django 3.1.6 on 2021-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210222_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='requirements_completed_percent_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprojectevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Project start'), (1, 'Progress update'), (2, 'Progress complete'), (3, 'Review request'), (11, 'Review message'), (12, 'Project complete'), (13, 'Project incomplete')]),
        ),
    ]
