# Generated by Django 3.1.6 on 2021-03-01 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20210223_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Progress'), (1, 'Pending Review'), (2, 'Complete'), (3, 'Incomplete')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprojectevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Project start'), (1, 'Progress update'), (2, 'Progress complete'), (3, 'Review request'), (10, 'Review message'), (11, 'Project complete'), (12, 'Project incomplete')]),
        ),
        migrations.CreateModel(
            name='UserProjectEventParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userproject')),
            ],
        ),
    ]
