# Generated by Django 3.1.6 on 2021-03-02 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20210301_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectEventParticipant',
            new_name='UserProjectParticipant',
        ),
    ]
