# Generated by Django 3.1.6 on 2021-03-03 12:13

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210302_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('order', models.SmallIntegerField(default=0)),
                ('cover', sorl.thumbnail.fields.ImageField(upload_to=projects.models.project_image_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
