# Generated by Django 3.1.6 on 2021-03-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='cover',
            new_name='image',
        ),
    ]
