# Generated by Django 3.1.6 on 2021-10-30 01:54

from django.db import migrations, models
import django.db.models.deletion
import roadmaps.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=roadmaps.models.roadmap_cover_path)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTopicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('roadmap_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='roadmaps.roadmaptopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['slug'], name='roadmap_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['status'], name='roadmap_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopiccontent',
            index=models.Index(fields=['order'], name='roadmap_topic_c_order_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['slug'], name='roadmap_topic_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['status'], name='roadmap_topic_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaptopic',
            index=models.Index(fields=['order'], name='roadmap_topic_order_idx'),
        ),
    ]
