# Generated by Django 3.1.6 on 2022-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (3, 'Deleted')], db_index=True, default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (3, 'Deleted')], db_index=True, default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (3, 'Deleted')], db_index=True, default=1, verbose_name='Status'),
        ),
    ]
