# Generated by Django 3.1.6 on 2022-07-09 15:37

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=courses.models.course_image_path)),
                ('video_url', models.CharField(blank=True, default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('public', models.BooleanField(default=False)),
                ('video_url', models.CharField(blank=True, default='', max_length=250)),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=courses.models.course_image_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.coursechapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLessonStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_statuses', to='courses.courseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_statuses', to='courses.courselesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='courselessonstatus',
            index=models.Index(fields=['enrollment', 'lesson', 'user'], name='enrollment_user_lesson_idx'),
        ),
        migrations.AddConstraint(
            model_name='courselessonstatus',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson', 'user'), name='unique_enrollment_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['slug'], name='course_lesson_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['order'], name='course_lesson_order_idx'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['status'], name='course_lesson_status_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'course'], name='user_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course'),
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['status'], name='course_chapter_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['order'], name='course_chapter_order_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='course_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_status_idx'),
        ),
    ]
