# Generated by Django 3.1.6 on 2021-09-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(63, 'javascript'), (71, 'python'), (60, 'go'), (72, 'ruby')], default=63, verbose_name='Language'),
        ),
    ]
